version: '3'
services:
  coordinator:
    build: .
    command: [ "/start_coordinator.sh" ]
    volumes:
      - ./test/testdata:/app/inputs:ro
    environment:
      - COORDINATOR_PORT=1234
      - N_REDUCE=10
      - WORKER_TIMEOUT=10
  worker:
    depends_on:
      - coordinator
    build: .
    command: [ "/worker", '/app/plugin.so' ]
    volumes:
      - ./test/testdata:/app/inputs:ro
      - ./out:/out
      - ./plugin.so:/app/plugin.so:ro
    environment:
      - COORDINATOR_HOST=coordinator
      - COORDINATOR_PORT=1234
